version: '3.7'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "<database_hostname>"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "<database_name>"
      DB_MYSQL_PASSWORD: "<database_password>"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  default:
    external:
      name: internal